# Generated by Django 3.0.3 on 2021-01-24 10:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionPartidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=255)),
                ('publicado', models.BooleanField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPartidos.Partidos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
